### ISSUE TITLE
Demo apps don't play sound (AudioContext not allowed to start)

### ISSUE THREAD

**Issue by SuperGoldenZ** [Thibor/jsRapPiano#3]
In Chrome at least, the demo apps <a href="https://thibor.github.io/jsRapPiano/">demo1</a> <a href="https://thibor.github.io/RapPiano/">demo2</a> don't generate sound, following message is shown in the console:

```
The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
```

I believe in Dec 2018 (ref: https://goo.gl/7K7WLu) Web Audio API was included in Chrome autoplay policy, so since then some user interaction is required before the AudioContext can be used to play sounds.

![image](https://user-images.githubusercontent.com/4214415/80729054-aa54ad80-8b42-11ea-92d3-4b789531c3ce.png)

**Comment by Thibor** [comment]
I make this plugin before 2018 now working when I setup chrome chrome://settings/content/sound, anyway I can try fix it in few day

**Comment by Thibor** [comment]
now is working for me, your link was very helpful thank you.

**Comment by SuperGoldenZ** [comment]
Thank you for the fast response.  The demo apps are working well for me now!

By the way - I'm not sure if intentional or not, but it looks like changes for the PR I made before to send note index when mousedown event happens were overwritten.

**Comment by Thibor** [comment]
Sorry it was accidental. I probably can't delete last commit on this website, but but I added it again.
